development:
  clients:
    default:
      database: mydatabase
      hosts:
        - localhost:27017
      options:
        user: myuser
        password: mypassword

test:
  clients:
    default:
      database: mydatabase_test
      hosts:
        - localhost:27017
      options:
        user: myuser
        password: mypassword

production:
  clients:
    default:
      database: mydatabase
      hosts:
        - <%= ENV['MONGODB_HOST'] %>:27017
      options:
        user: <%= ENV['MONGODB_USER'] %>
        password: <%= ENV['MONGODB_PASSWORD'] %>
