# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gameOfAi.proto for package 'gameOfAi'

require 'grpc'
require 'gameOfAi_pb'

module GameOfAi
  module GameOfLife
    # Servizio GameOfLife
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gameOfAi.GameOfLife'

      rpc :ProcessFile, ::GameOfAi::GameOfLifeRequest, ::GameOfAi::GameOfLifeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
